# Generated by Django 3.0.8 on 2020-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20200713_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.TextField(blank=True, max_length=500, verbose_name='Ответ'),
        ),
    ]
