# Generated by Django 3.0.8 on 2020-07-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20200713_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=1050, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.TextField(blank=True, max_length=1050, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, max_length=1050, verbose_name='Текст'),
        ),
    ]
